server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 201550
    url: jdbc:mysql://localhost:3306/mall-marketing?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
